config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'tasks#index', as: :authenticated_root
    end

    unauthenticated :user do
      root "welcome#index", as: :unauthenticated_root
    end
  end
  
  resources :tasks do
    resources :notes, only: [:create], controller: 'tasks/notes'
  end
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  due_date    :date
#  category_id :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  owner_id    :bigint           not null
#  code        :string
#  is_deleted  :boolean          default(FALSE)
#
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :owner, class_name: 'User'
  has_many :participating_users, class_name: 'Participant', dependent: :destroy
  has_many :participants, through: :participating_users, source: :user
  has_many :notes, dependent: :destroy

  #Validations
  validates :name, :description, :participating_users, presence: true
  validates :name, uniqueness: { case_insensitive: false }
  validate :due_date_validity

  #CALLBACKS
  before_create :create_code
  after_create :send_email

  accepts_nested_attributes_for :participating_users, allow_destroy: true

  def due_date_validity
    return if due_date.blank?
    return if due_date > Date.today
    errors.add :due_date, I18n.t('task.errors.invalid_due_date')
  end

  def create_code
    self.code = "#{owner_id}#{Time.now.to_i.to_s(36)}#{SecureRandom.hex(8)}"
  end

  def send_email
    (participants + [owner]).each do |user|
      ParticipantMailer.with(user: user, task: self).new_task_email.deliver!
    end
  end
end

app/controllers/tasks/notes_controller.rb
class Tasks::NotesController < ApplicationController
  before_action :set_task


  def create
    @note = @task.notes.new(note_params)
    @note.user = current_user
    @note.save!
    render 'tasks/show', task: @task
  end

  private
    def set_task
      @task = Task.find(params[:task_id])
    end

    def note_params
      params.require(:note).permit(:body)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    #@tasks = Task.all.where(owner_id == current_user.id)
    @tasks = Task.joins(:participants).where(
      'owner_id = ? OR participants.user_id = ?',
      current_user.id,
      current_user.id
    ).group(:id)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.owner = current_user
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(
        :name,
        :description,
        :due_date,
        :category_id,
        participating_users_attributes: [
          :id,
          :user_id,
          :role,
          :_destroy
        ])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@task) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: t('.name')
    = f.input :description, label: t('.description')
    = f.input :due_date, label: t('.due_date')
    = f.association :category, label: t('.category')
    #addParticipants
      = link_to_add_association f, :participating_users, 'data-association-insertion-node' => '.partipants .participants-container', 'data-turbolinks' => false do
        Agregar participante
    .partipants
      = f.simple_fields_for :participating_users do |g|
        = render 'participating_user_fields', f: g
      .participants-container

  .form-actions
    = f.button :submit

app/views/tasks/_participating_user_fields.html.haml
.nested_fields
  = f.input :user_id, as: :select, collection: User.all - [current_user], label_method: :email
  = f.input :role, label: 'Rol', as: :select, collection: Participant.roles, value_method: -> (r) { r[0] }

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1= t('tasks.listing_tasks')

%table.table
  %thead
    %tr
      %th= t('tasks.name')
      %th= t('tasks.description')
      %th= t('tasks.due_date')
      %th= t('tasks.category')
      %th Created_by
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.name
        %td= task.description
        %td= task.due_date
        %td= task.category.name
        %td= task.owner.email
        %td= link_to t('common.show'), task
        %td= link_to t('common.edit'), edit_task_path(task)
        %td= button_to t('common.destroy'), task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to t('tasks.new_task'), new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to t('common.back'), tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @task.name
%p
  %b Description:
  = @task.description
%p
  %b Due date:
  = @task.due_date
%p
  %b Category:
  = @task.category.name

.notes-container
  - @task.notes.each do |note|
    %p= note.body
    %p= time_ago_in_words note.created_at
    %p= note.user.email
    %hr

  = simple_form_for Note.new, url: task_notes_path(task_id: @task.id) do |f|
    = f.input :body, label: false, as: :string, placeholder: 'Escribe tu nota', input_html: { autocomplete: 'off' }

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path